#!/bin/bash

#
# stubby smash script
#
# Copyright (c) 2020,2021 Cisco Systems, Inc. <pmoore2@cisco.com>
#

#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# NOTE: this file exists for compatibility with existing scripts, you really
#       should be calling stubby-smash.1.sh (or later) directly; if you need
#       SBAT support, you MUST call stubby-smash.1.sh directly

exec stubby-smash.1.sh -k $1 -i $2 -c $3 -o $4
