name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --quiet --assume-yes --no-install-recommends gnu-efi build-essential
          sudo apt-get install --quiet --assume-yes --no-install-recommends dosfstools mtools ovmf qemu-system-x86 qemu-utils
      - name: Build
        run: |
          make build
      - name: Unit Test
        run: |
          make test
